# Copyright (C) Markus Franz Xaver Johannes Oberhumer
#
#

name: 'CC - container Alpine clang'
'on':
  schedule: [cron: '00 1 * * 2'] # run weekly Tuesday 01:00 UTC
  workflow_dispatch: null
env:
  CMAKE_REQUIRED_QUIET: 'OFF'
  CMAKE_VERBOSE_MAKEFILE: 'ON'
  CTEST_OUTPUT_ON_FAILURE: 'ON'
  DEBIAN_FRONTEND: noninteractive
  UPX_CMAKE_CONFIG_FLAGS: -Wdev --warn-uninitialized
  UPX_CONFIG_EXPECT_THREADS: 'ON'
  VERBOSE: 1

  # these are exactly like the GITHUB_xxx default environment variables
  REMOTE_REF_NAME: devel
  REMOTE_REF_TYPE: branch         # branch OR tag
  REMOTE_REPOSITORY: upx/upx
  REMOTE_SERVER_URL: https://github.com
  REMOTE_SHA: '0000000000000000000000000000000000000000' # will get updated below

jobs:
  clang: # uses cmake + make
    if: github.repository_owner == 'upx'

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # info: "static-works" means that using "clang -static" should work
          # { container: 'alpine:3.9' }  # clang-5.0.2        BROKEN: test crashes; static-works
          - { container: 'alpine:3.10' } # clang-8.0.0
          - { container: 'alpine:3.11' } # clang-9.0.0
          - { container: 'alpine:3.12' } # clang-10.0.0       QEMU is broken
          - { container: 'alpine:3.13' } # clang-10.0.1
          - { container: 'alpine:3.14' } # clang-11.1.0
          - { container: 'alpine:3.15' } # clang-12.0.1
          - { container: 'alpine:3.16' } # clang-13.0.1
          - { container: 'alpine:3.17' } # clang-15.0.7
          - { container: 'alpine:3.18' } # clang-16.0.6
          - { container: 'alpine:3.19' } # clang-17.0.5
          - { container: 'alpine:edge' } # clang-17.0.5
          # 32-bit i386 versions
          # { container: 'i386/alpine:3.9' }  # clang-5.0.2   BROKEN: build fails
          # { container: 'i386/alpine:3.10' } # clang-8.0.0   BROKEN: test crashes; static-works
          # { container: 'i386/alpine:3.11' } # clang-9.0.0   BROKEN: test crashes; static-works
          - { container: 'i386/alpine:3.12' } # clang-10.0.0  QEMU is broken
          - { container: 'i386/alpine:3.13' } # clang-10.0.1
          - { container: 'i386/alpine:3.14' } # clang-11.1.0
          - { container: 'i386/alpine:3.15' } # clang-12.0.1
          - { container: 'i386/alpine:3.16' } # clang-13.0.1
          - { container: 'i386/alpine:3.17' } # clang-15.0.7
          - { container: 'i386/alpine:3.18' } # clang-16.0.6
          - { container: 'i386/alpine:3.19' } # clang-17.0.5
          - { container: 'i386/alpine:edge' } # clang-17.0.5

    env:
      CC: 'clang'
      CXX: 'clang++'

    steps:

      - name: 'Display environment'
        run: |
          uname -a; pwd; id; umask
          env | LC_ALL=C sort

      - name: ${{ format('Install packages {0}', matrix.container) }}
        run: |
          apk update && apk upgrade && apk add cmake clang git make
          case ${{ matrix.container }} in
            # g++ is needed on Alpine <= 3.18 because of missing dependencies
            *:3.[0-9] | *:3.1[0-8]) apk add g++ ;;
          esac
          case ${{ matrix.container }} in
            # clang-dev is needed on Alpine <= 3.11 for clang headers like <emmintrin.h>
            *:3.[0-9] | *:3.1[0-1]) apk add clang-dev ;;
          esac
          case ${{ matrix.container }} in
            # llvm-dev is needed on Alpine <= 3.18 for -flto (-flto only works on Alpine >= 3.15)
            *:3.1[5-8]) apk add llvm-dev ;;
          esac

      - name: ${{ format('Check out {0}/{1} {2} {3} source code', env.REMOTE_SERVER_URL, env.REMOTE_REPOSITORY, env.REMOTE_REF_TYPE, env.REMOTE_REF_NAME) }}
        run: |
          # git config
          git config --global core.autocrlf false
          git config --global --add safe.directory '*'
          # install Self, needed for config file below
          ##git clone --branch "$GITHUB_REF_NAME" --depth 1 "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" ../Self

          git clone --branch "$REMOTE_REF_NAME" --depth 1 "$REMOTE_SERVER_URL/$REMOTE_REPOSITORY" .
          test -f ./.gitmodules && git submodule update --init
          # TODO: handle REMOTE_REF_TYPE == "tag"
          # update environment
          rev="$(git rev-parse HEAD)"
          echo "REMOTE_SHA=$rev" >> $GITHUB_ENV

      - name: ${{ format('Build Debug with {0} and {1}', env.CC, env.CXX) }}
        run: 'make build/debug'
      - name: ${{ format('Build Release with {0} and {1}', env.CC, env.CXX) }}
        run: 'make build/release'

      - name: 'Run tests'
        run: |
          # INFO: "ctest --test-dir DIR" only works on Alpine >= 3.14 (cmake-3.20.6)
          (cd build/debug && ctest)
          (cd build/release && ctest)
          if test -f ./misc/testsuite/test_symlinks.sh; then true;
            apk add bash sudo
            # IMPORTANT: do NOT run as user root!
            (cd build/release && chmod a+w . && sudo -u operator bash ../../misc/testsuite/test_symlinks.sh)
          fi
          true

      - name: Mimic ctest tests
        run: |
          if test -f ./misc/testsuite/mimic_ctest.sh; then true;
            apk add bash
            (cd build/debug && bash ../../misc/testsuite/mimic_ctest.sh)
            (cd build/release && bash ../../misc/testsuite/mimic_ctest.sh)
          fi
          true

      - name: Mimic ctest tests QEMU
        run: |
          if test -f ./misc/testsuite/mimic_ctest.sh; then true;
            case ${{ matrix.container }} in
              # qemu-5.0.0-r2 on Alpine 3.12 crashes on "./upx-packed.out --version-short" (both under i386 and x86_64)
              *:3.12) echo "QEMU is broken -- tests skipped"; exit 0 ;;
              i386/*) apk add bash qemu-i386; export upx_exe_runner=qemu-i386 ;;
              *)      apk add bash qemu-x86_64; export upx_exe_runner=qemu-x86_64 ;;
            esac
            (cd build/debug && bash ../../misc/testsuite/mimic_ctest.sh)
            (cd build/release && bash ../../misc/testsuite/mimic_ctest.sh)
          fi
          true
